package com.vaan.behindthecurtain

import android.content.*
import android.graphics.*
import android.media.MediaMetadataRetriever
import android.net.Uri
import android.os.*
import android.provider.MediaStore
import android.widget.*
import androidx.activity.result.contract.ActivityResultContracts
import androidx.appcompat.app.AppCompatActivity
import java.util.concurrent.Executors
import kotlin.math.max
import kotlin.math.min

class ForensicLabActivity:AppCompatActivity(){
    private val ex=Executors.newSingleThreadExecutor();private lateinit var st:TextView;private lateinit var image:ImageView
    private val imagePick=registerForActivityResult(ActivityResultContracts.OpenDocument()){u->if(u!=null)scanImage(u)}
    private val videoPick=registerForActivityResult(ActivityResultContracts.OpenDocument()){u->if(u!=null)scanVideo(u)}
    private val audioPick=registerForActivityResult(ActivityResultContracts.OpenDocument()){u->if(u!=null)scanAudio(u)}
    private val templatePick=registerForActivityResult(ActivityResultContracts.OpenDocument()){u->if(u!=null)contentResolver.openInputStream(u)?.use{ins->BitmapFactory.decodeStream(ins)?.let{b->val n=TemplateStore.add(this,b);st.text="Saved symbol template: $n"}}}
    override fun onCreate(b:Bundle?){super.onCreate(b);val r=Ui.root(this);r.addView(Ui.title(this,"FORENSIC LAB v1.3"));r.addView(Ui.body(this,"Import images, video or audio. v1.3 adds transform-consensus visual analysis, structural symbol candidates, full-timeline video sampling, spectral/carrier checks, prosody shifts and defensive language-pattern flags."));r.addView(Ui.button(this,"SCAN IMAGE"){imagePick.launch(arrayOf("image/*"))});r.addView(Ui.button(this,"SCAN VIDEO"){videoPick.launch(arrayOf("video/*"))});r.addView(Ui.button(this,"SCAN AUDIO"){audioPick.launch(arrayOf("audio/*"))});r.addView(Ui.button(this,"ADD SYMBOL / SHAPE TEMPLATE"){templatePick.launch(arrayOf("image/*"))});image=ImageView(this).apply{adjustViewBounds=true};r.addView(image,LinearLayout.LayoutParams(-1,Ui.dp(this,280)));st=Ui.body(this,"Ready.").apply{setTextIsSelectable(true)};r.addView(ScrollView(this).apply{addView(st)},LinearLayout.LayoutParams(-1,0,1f));setContentView(r)}

    private fun scanImage(u:Uri){st.text="Running deep image analysis…";ex.execute{try{val b=contentResolver.openInputStream(u)?.use{BitmapFactory.decodeStream(it)}?:return@execute;val deep=V13VisualAnalyzer.deep(this,b);val base=(VisualEngine.scan(b)+OcrEngine.scan(b,true)+TemplateMatcher.scan(b,TemplateStore.load(this))+deep.first).sortedByDescending{it.confidence}.distinctBy{it.label+it.rect.left.toInt()+it.rect.top.toInt()}.take(55);EvidenceStore.visual(this,b,base);runOnUiThread{image.setImageBitmap(mark(b,base));st.text=buildString{append("Found ${base.size} candidates.\n\n");base.take(45).forEachIndexed{i,d->append("${i+1}. ${d.label} • ${(d.confidence*100).toInt()}%\n")};if(deep.second.isNotEmpty()){append("\nTRANSFORM / OCR NOTES\n");deep.second.forEach{append("• $it\n")}}}}}catch(t:Throwable){runOnUiThread{st.text="Image scan error: ${t.message}"}}}}

    private fun scanVideo(u:Uri){st.text="Scanning complete video timeline…";ex.execute{val r=MediaMetadataRetriever();try{r.setDataSource(this,u);val dur=r.extractMetadata(MediaMetadataRetriever.METADATA_KEY_DURATION)?.toLongOrNull()?:0L;val step=max(250L,if(dur>0)dur/3600L else 250L);val temporal=TemporalEngine();val templates=TemplateStore.load(this);var t=0L;var frames=0;var hits=0;var best=0f;var bestFrame:Bitmap?=null;var bestDs:List<Detection> = emptyList();val notes=StringBuilder();while(t<=dur){val b=r.getFrameAtTime(t*1000,MediaMetadataRetriever.OPTION_CLOSEST);if(b!=null){frames++;val ocr=if(frames%4==1)OcrEngine.scan(b,true)else emptyList();val ds=mutableListOf<Detection>();ds+=VisualEngine.scan(b);ds+=temporal.scan(b);ds+=V13SymbolEngine.scan(b);ds+=ocr;ds+=TemplateMatcher.scan(b,templates);if(frames%16==1)ds+=V13VisualAnalyzer.deep(this,b).first.take(10);val sorted=ds.sortedByDescending{it.confidence}.take(36);val top=sorted.firstOrNull()?.confidence?:0f;if(top>=.74f){hits++;if(notes.lines().size<220)notes.append("${"%.2f".format(t/1000.0)}s: ${(top*100).toInt()}% ${sorted.firstOrNull()?.label}\n");if(top>best){best=top;bestFrame=b.copy(Bitmap.Config.ARGB_8888,false);bestDs=sorted};if(top>=.90f)EvidenceStore.visual(this,b,sorted)}};if(frames%20==0)runOnUiThread{st.text="Video: ${t/1000}s / ${dur/1000}s • $hits candidate frames"};t+=step};runOnUiThread{bestFrame?.let{image.setImageBitmap(mark(it,bestDs))};st.text="Video scan complete.\nFrames sampled: $frames\nCandidate frames: $hits\nSample step: ${step}ms\n\n$notes"}}finally{r.release()}}}

    private fun scanAudio(u:Uri){st.text="Decoding audio…";ex.execute{val d=try{AudioFileDecoder.decode(this,u)}catch(_:Throwable){null};if(d==null){runOnUiThread{st.text="Could not decode this audio file."};return@execute};val fs=V13AudioDeep.signalFindings(d.pcm,d.rate);val prosody=V13ProsodyAnalyzer.analyze(d.pcm,d.rate);val carrier=V13AudioDeep.carrierNote(d.pcm,d.rate);val sample=speechSample(d.pcm,d.rate);SpeechDecoder.decode(this,sample,d.rate){words->val language=V13LanguageAnalyzer.fromDecoderLines(words);val strongest=fs.maxByOrNull{it.confidence};val archiveFinding=strongest?:if(words.isNotEmpty())AudioFinding("SPEECH / TRANSFORM CANDIDATE",0.70f,0f,-120f,"forward, reversed and speed-shift speech sweep")else null;archiveFinding?.let{EvidenceStore.audio(this,sample,d.rate,it,words)};runOnUiThread{image.setImageDrawable(null);st.text=buildString{append("Audio scan complete.\nRate: ${d.rate} Hz\nSignal findings: ${fs.size}\n");fs.take(25).forEach{append("• ${(it.confidence*100).toInt()}% ${it.label} @ ${"%.1f".format(it.peakHz)} Hz • ${it.detail}\n")};carrier?.let{append("• $it\n")};append("\nSUBTITLE / WORD CANDIDATES\n");if(words.isEmpty())append("No stable speech candidate.\n")else words.take(20).forEach{append("• $it\n")};append("\nPROSODY SHIFTS\n");prosody.take(25).forEach{append("• $it\n")};append("\nLANGUAGE PATTERNS\n");language.take(25).forEach{append("• ${it.category}: ${it.excerpt} (${(it.confidence*100).toInt()}%)\n")}}}}}}

    private fun speechSample(pcm:ShortArray,rate:Int):ShortArray{val max=rate*30;if(pcm.size<=max)return pcm;val chunk=rate*10;val starts=intArrayOf(0,((pcm.size-chunk)/2).coerceAtLeast(0),(pcm.size-chunk).coerceAtLeast(0));val out=ShortArray(chunk*3);var dst=0;for(s in starts){val n=min(chunk,pcm.size-s);System.arraycopy(pcm,s,out,dst,n);dst+=n};return if(dst==out.size)out else out.copyOf(dst)}
    private fun mark(b:Bitmap,ds:List<Detection>):Bitmap{val o=b.copy(Bitmap.Config.ARGB_8888,true);val c=Canvas(o);val p=Paint(Paint.ANTI_ALIAS_FLAG).apply{style=Paint.Style.STROKE;strokeWidth=maxOf(3f,b.width/300f);color=Color.CYAN};val t=Paint(Paint.ANTI_ALIAS_FLAG).apply{color=Color.YELLOW;textSize=max(20f,b.width/42f);typeface=Typeface.DEFAULT_BOLD};ds.take(35).forEach{c.drawRect(it.rect,p);c.drawText(it.label.take(48),it.rect.left,max(t.textSize,it.rect.top-4),t)};return o}
    override fun onDestroy(){ex.shutdownNow();super.onDestroy()}
}

class VaultActivity:AppCompatActivity(){
    override fun onCreate(b:Bundle?){super.onCreate(b);val r=Ui.root(this);r.addView(Ui.title(this,"BEHIND THE CURTAIN"));r.addView(Ui.body(this,"Auto-saved evidence. Tap a file to open it. Evidence is stored under Download/BehindTheCurtain/<date>/."));val list=ListView(this);r.addView(list,LinearLayout.LayoutParams(-1,0,1f));setContentView(r);val names=mutableListOf<String>();val uris=mutableListOf<Uri>();if(Build.VERSION.SDK_INT>=29){val cols=arrayOf(MediaStore.MediaColumns._ID,MediaStore.MediaColumns.DISPLAY_NAME);contentResolver.query(MediaStore.Downloads.EXTERNAL_CONTENT_URI,cols,"${MediaStore.MediaColumns.RELATIVE_PATH} LIKE ?",arrayOf("Download/BehindTheCurtain/%"),"${MediaStore.MediaColumns.DATE_ADDED} DESC")?.use{c->val ii=c.getColumnIndexOrThrow(MediaStore.MediaColumns._ID);val ni=c.getColumnIndexOrThrow(MediaStore.MediaColumns.DISPLAY_NAME);while(c.moveToNext()){names+=c.getString(ni);uris+=ContentUris.withAppendedId(MediaStore.Downloads.EXTERNAL_CONTENT_URI,c.getLong(ii))}}};list.adapter=ArrayAdapter(this,android.R.layout.simple_list_item_1,names);list.setOnItemClickListener{_,_,p,_->val u=uris[p];val m=contentResolver.getType(u)?:"*/*";try{startActivity(Intent(Intent.ACTION_VIEW).setDataAndType(u,m).addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION))}catch(_:Throwable){Toast.makeText(this,"Saved: ${names[p]}",Toast.LENGTH_SHORT).show()}}}
}
