package com.omega.synesthesia;

import android.Manifest;import android.app.*;import android.os.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.*;import android.hardware.*;import android.media.*;import android.speech.tts.TextToSpeech;import android.view.*;import android.widget.*;import java.util.*;

public class MainActivity extends Activity implements SensorEventListener {
 private final FusionEngine engine=new FusionEngine(); private SensorManager sm; private Sensor accel,gyro,mag,light; private float vib,rot,magV,lightDelta,lastLight; private AudioRecord audio; private Thread audioThread; private volatile boolean running; private float audioEnergy,visualMotion; private TextView state,detail,metrics; private SynesthesiaView field; private TextToSpeech tts; private String lastSpoken=""; private long lastSpeak;
 @Override public void onCreate(Bundle b){super.onCreate(b); buildUi(); sm=(SensorManager)getSystemService(SENSOR_SERVICE);accel=sm.getDefaultSensor(Sensor.TYPE_ACCELEROMETER);gyro=sm.getDefaultSensor(Sensor.TYPE_GYROSCOPE);mag=sm.getDefaultSensor(Sensor.TYPE_MAGNETIC_FIELD);light=sm.getDefaultSensor(Sensor.TYPE_LIGHT);tts=new TextToSpeech(this,s->{ }); if(Build.VERSION.SDK_INT>=23 && checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED) requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},7); else startAudio(); new Handler().postDelayed(tick,120);}
 private void buildUi(){ LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(24,18,24,20);root.setBackgroundColor(Color.rgb(5,7,11));
  TextView title=t("Ω SYNESTHESIA",30,Color.WHITE);root.addView(title);root.addView(t("One perception. Sight, sound, vibration, motion, light and magnetic change fused together.",15,Color.LTGRAY));
  field=new SynesthesiaView(this);root.addView(field,new LinearLayout.LayoutParams(-1,0,1)); state=t("AWAKENING",25,Color.rgb(103,247,231));root.addView(state); detail=t("Learning how this environment feels…",17,Color.WHITE);detail.setPadding(0,8,0,10);root.addView(detail);metrics=t("",14,Color.GRAY);root.addView(metrics);
  Button recal=new Button(this);recal.setText("RELEARN ENVIRONMENT");recal.setOnClickListener(v->recreate());root.addView(recal);setContentView(root); }
 private TextView t(String s,int z,int color){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(color);v.setPadding(0,5,0,5);return v;}
 @Override protected void onResume(){super.onResume();for(Sensor s:new Sensor[]{accel,gyro,mag,light})if(s!=null)sm.registerListener(this,s,SensorManager.SENSOR_DELAY_GAME);}
 @Override protected void onPause(){super.onPause();sm.unregisterListener(this);}
 @Override protected void onDestroy(){running=false;if(audio!=null){try{audio.stop();audio.release();}catch(Exception ignored){}}if(tts!=null)tts.shutdown();super.onDestroy();}
 @Override public void onSensorChanged(SensorEvent e){float m=0;for(float x:e.values)m+=x*x;m=(float)Math.sqrt(m);if(e.sensor==accel)vib=Math.abs(m-9.80665f);else if(e.sensor==gyro)rot=m;else if(e.sensor==mag)magV=m;else if(e.sensor==light){if(lastLight>0)lightDelta=Math.abs(e.values[0]-lastLight)/Math.max(1,lastLight);lastLight=e.values[0];}}
 @Override public void onAccuracyChanged(Sensor s,int a){}
 private void startAudio(){try{int rate=16000, min=AudioRecord.getMinBufferSize(rate,AudioFormat.CHANNEL_IN_MONO,AudioFormat.ENCODING_PCM_16BIT);audio=new AudioRecord(MediaRecorder.AudioSource.UNPROCESSED,rate,AudioFormat.CHANNEL_IN_MONO,AudioFormat.ENCODING_PCM_16BIT,Math.max(min,4096));audio.startRecording();running=true;audioThread=new Thread(()->{short[] b=new short[1024];while(running){int n=audio.read(b,0,b.length);double q=0;for(int i=0;i<n;i++)q+=(double)b[i]*b[i];if(n>0)audioEnergy=(float)Math.sqrt(q/n)/32768f;}});audioThread.start();}catch(Exception e){audioEnergy=0;}}
 private final Runnable tick=new Runnable(){public void run(){visualMotion=0;FusionEngine.Percept p=engine.fuse(visualMotion,audioEnergy,vib,rot,magV,lightDelta);state.setText(p.statement);detail.setText(p.detail);metrics.setText("Ω coherence "+Math.round(p.coherence*100)+"%   •   novelty "+Math.round(p.novelty*100)+"%   •   intensity "+Math.round(p.intensity*100)+"%");field.setPercept(p);if((p.statement.contains("COHERENT")||p.statement.contains("UNKNOWN"))&&!p.statement.equals(lastSpoken)&&System.currentTimeMillis()-lastSpeak>3500){tts.speak(p.statement+". "+p.detail,TextToSpeech.QUEUE_FLUSH,null,"omega");lastSpoken=p.statement;lastSpeak=System.currentTimeMillis();}vib*=.78f;rot*=.82f;lightDelta*=.75f;new Handler().postDelayed(this,150);}};
 @Override public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);if(r==7&&g.length>0&&g[0]==PackageManager.PERMISSION_GRANTED)startAudio();}
}
