package com.omega.synesthesia;

import android.Manifest;import android.app.Activity;import android.content.Context;import android.content.pm.PackageManager;import android.graphics.Color;import android.graphics.SurfaceTexture;import android.hardware.*;import android.hardware.camera2.*;import android.media.*;import android.os.*;import android.speech.tts.TextToSpeech;import android.view.*;import android.widget.*;import java.nio.ByteBuffer;import java.util.*;

public class MainActivity extends Activity implements SensorEventListener,TextToSpeech.OnInitListener{
 private static final int REQ=71; private final FusionEngine fusion=new FusionEngine(); private final CrossSenseEngine cross=new CrossSenseEngine(); private final CameraSense cameraSense=new CameraSense(); private final ActiveProbeEngine probe=new ActiveProbeEngine();
 private SensorManager sm;private Sensor accel,gyro,mag,light;private volatile float vibration,rotation,magnetic,lightDelta,lastLight,audioEnergy,visualMotion,cameraLightChange,leftMotion,rightMotion;private AudioRecord audio;private Thread audioThread;private volatile boolean audioRunning;
 private HandlerThread cameraThread;private Handler cameraHandler;private CameraDevice camera;private CameraCaptureSession cameraSession;private ImageReader imageReader;private TextureView preview;private SynesthesiaView field;private TextView state,detail,crossReadout,probeReadout;private TextToSpeech tts;private boolean ttsReady;private String lastSpoken="";private long lastSpeak;private int blindMode=0;private boolean activeProbe=false;private float probeBefore;private long probeStart;private final Handler ui=new Handler();
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(Color.rgb(5,7,11));getWindow().setNavigationBarColor(Color.rgb(5,7,11));buildUi();sm=(SensorManager)getSystemService(SENSOR_SERVICE);accel=sm.getDefaultSensor(Sensor.TYPE_ACCELEROMETER);gyro=sm.getDefaultSensor(Sensor.TYPE_GYROSCOPE);mag=sm.getDefaultSensor(Sensor.TYPE_MAGNETIC_FIELD);light=sm.getDefaultSensor(Sensor.TYPE_LIGHT);tts=new TextToSpeech(this,this);if(!permissionsReady())requestPermissions(new String[]{Manifest.permission.CAMERA,Manifest.permission.RECORD_AUDIO},REQ);else startPerception();ui.postDelayed(tick,160);}
 private void buildUi(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(22,14,22,16);root.setBackgroundColor(Color.rgb(5,7,11));root.addView(text("Ω SYNESTHESIA v0.3",27,Color.WHITE));root.addView(text("One field • cross-sense completion • active environmental probing",14,0xFF9EB2BA));preview=new TextureView(this);preview.setSurfaceTextureListener(surfaceListener);root.addView(preview,new LinearLayout.LayoutParams(-1,dp(135)));field=new SynesthesiaView(this);root.addView(field,new LinearLayout.LayoutParams(-1,0,1));state=text("AWAKENING",24,0xFF67F7E7);state.setGravity(17);root.addView(state);detail=text("Learning how this environment feels.",16,Color.WHITE);detail.setGravity(17);root.addView(detail);crossReadout=text("Cross-sense model warming up…",14,0xFFFFD37A);crossReadout.setGravity(17);root.addView(crossReadout);probeReadout=text("ACTIVE PROBE OFF",14,0xFF9EB2BA);probeReadout.setGravity(17);root.addView(probeReadout);
  LinearLayout c=new LinearLayout(this);Button blind=new Button(this);blind.setText("ALL SENSES");blind.setOnClickListener(v->{blindMode=(blindMode+1)%3;blind.setText(blindMode==0?"ALL SENSES":blindMode==1?"BLIND VISION":"BLIND HEARING");});c.addView(blind,new LinearLayout.LayoutParams(0,dp(50),1));Button ap=new Button(this);ap.setText("PROBE OFF");ap.setOnClickListener(v->{activeProbe=!activeProbe;ap.setText(activeProbe?"PROBE ON":"PROBE OFF");probeReadout.setText(activeProbe?"ACTIVE PROBE ARMED • coded high-frequency chirps":"ACTIVE PROBE OFF");if(activeProbe)scheduleProbe();});c.addView(ap,new LinearLayout.LayoutParams(0,dp(50),1));root.addView(c);Button rel=new Button(this);rel.setText("RELEARN ENVIRONMENT");rel.setOnClickListener(v->recreate());root.addView(rel);setContentView(root);}
 private TextView text(String s,int z,int color){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(color);v.setPadding(0,4,0,4);return v;}
 @Override public void onInit(int s){if(s==TextToSpeech.SUCCESS&&tts!=null){ttsReady=tts.setLanguage(Locale.US)>=0;if(ttsReady){tts.setSpeechRate(.96f);tts.setPitch(.95f);}}}
 @Override protected void onResume(){super.onResume();if(sm!=null)for(Sensor s:new Sensor[]{accel,gyro,mag,light})if(s!=null)sm.registerListener(this,s,SensorManager.SENSOR_DELAY_GAME);if(permissionsReady())startPerception();}
 @Override protected void onPause(){closeCamera();if(sm!=null)sm.unregisterListener(this);super.onPause();}@Override protected void onDestroy(){activeProbe=false;stopAudio();stopCameraThread();if(tts!=null){tts.stop();tts.shutdown();}super.onDestroy();}
 @Override public void onSensorChanged(SensorEvent e){float m=0;for(float x:e.values)m+=x*x;m=(float)Math.sqrt(m);if(e.sensor==accel)vibration=Math.abs(m-9.80665f);else if(e.sensor==gyro)rotation=m;else if(e.sensor==mag)magnetic=m;else if(e.sensor==light){if(lastLight>0)lightDelta=Math.abs(e.values[0]-lastLight)/Math.max(1,lastLight);lastLight=e.values[0];}}@Override public void onAccuracyChanged(Sensor s,int a){}
 private boolean permissionsReady(){return checkSelfPermission(Manifest.permission.CAMERA)==PackageManager.PERMISSION_GRANTED&&checkSelfPermission(Manifest.permission.RECORD_AUDIO)==PackageManager.PERMISSION_GRANTED;}private void startPerception(){startAudio();startCameraThread();if(preview!=null&&preview.isAvailable())openCamera();}
 private void startAudio(){if(audioRunning)return;try{int rate=48000,min=AudioRecord.getMinBufferSize(rate,AudioFormat.CHANNEL_IN_MONO,AudioFormat.ENCODING_PCM_16BIT);audio=new AudioRecord(MediaRecorder.AudioSource.UNPROCESSED,rate,AudioFormat.CHANNEL_IN_MONO,AudioFormat.ENCODING_PCM_16BIT,Math.max(8192,min));audio.startRecording();audioRunning=true;audioThread=new Thread(()->{short[] b=new short[2048];while(audioRunning){int n=audio.read(b,0,b.length);double q=0;for(int i=0;i<n;i++)q+=(double)b[i]*b[i];if(n>0)audioEnergy=(float)Math.sqrt(q/n)/32768f;}},"OmegaAudio");audioThread.start();}catch(Exception e){audioEnergy=0;}}
 private void stopAudio(){audioRunning=false;try{if(audio!=null){audio.stop();audio.release();}}catch(Exception ignored){}audio=null;}
 private void scheduleProbe(){if(!activeProbe)return;ui.postDelayed(()->{if(!activeProbe||probe.isProbing())return;probeBefore=audioEnergy;probeStart=System.nanoTime();probe.probe(r->ui.postDelayed(()->{long ms=(System.nanoTime()-probeStart)/1_000_000L;ActiveProbeEngine.Reading scored=probe.score(probeBefore,audioEnergy,ms);String s=scored.confidence>.65f?"ENVIRONMENTAL RESPONSE CHANGED":scored.confidence>.3f?"Possible echo-field change":"Probe response near learned baseline";probeReadout.setText("ACTIVE PROBE • "+s+" • "+Math.round(scored.confidence*100)+"% change confidence");if(scored.confidence>.65f&&ttsReady)tts.speak("Environmental response changed.",TextToSpeech.QUEUE_ADD,null,"probe");scheduleProbe();},180));},1600);}
 private void startCameraThread(){if(cameraThread!=null)return;cameraThread=new HandlerThread("OmegaVision");cameraThread.start();cameraHandler=new Handler(cameraThread.getLooper());}private void stopCameraThread(){if(cameraThread==null)return;cameraThread.quitSafely();try{cameraThread.join();}catch(Exception ignored){}cameraThread=null;cameraHandler=null;}
 private final TextureView.SurfaceTextureListener surfaceListener=new TextureView.SurfaceTextureListener(){public void onSurfaceTextureAvailable(SurfaceTexture s,int w,int h){if(permissionsReady()){startCameraThread();openCamera();}}public void onSurfaceTextureSizeChanged(SurfaceTexture s,int w,int h){}public boolean onSurfaceTextureDestroyed(SurfaceTexture s){return true;}public void onSurfaceTextureUpdated(SurfaceTexture s){}};
 private void openCamera(){if(camera!=null||cameraHandler==null||!permissionsReady())return;try{CameraManager cm=(CameraManager)getSystemService(Context.CAMERA_SERVICE);String chosen=null;for(String id:cm.getCameraIdList()){Integer f=cm.getCameraCharacteristics(id).get(CameraCharacteristics.LENS_FACING);if(f!=null&&f==CameraCharacteristics.LENS_FACING_BACK){chosen=id;break;}}if(chosen==null&&cm.getCameraIdList().length>0)chosen=cm.getCameraIdList()[0];if(chosen!=null)cm.openCamera(chosen,cameraState,cameraHandler);}catch(Exception e){crossReadout.setText("Camera sense unavailable");}}
 private final CameraDevice.StateCallback cameraState=new CameraDevice.StateCallback(){public void onOpened(CameraDevice c){camera=c;createCameraSession();}public void onDisconnected(CameraDevice c){c.close();camera=null;}public void onError(CameraDevice c,int e){c.close();camera=null;}};
 private void createCameraSession(){try{SurfaceTexture st=preview.getSurfaceTexture();if(st==null||camera==null)return;st.setDefaultBufferSize(640,480);Surface ps=new Surface(st);imageReader=ImageReader.newInstance(320,240,android.graphics.ImageFormat.YUV_420_888,2);imageReader.setOnImageAvailableListener(this::onImage,cameraHandler);CaptureRequest.Builder r=camera.createCaptureRequest(CameraDevice.TEMPLATE_PREVIEW);r.addTarget(ps);r.addTarget(imageReader.getSurface());r.set(CaptureRequest.CONTROL_AF_MODE,CaptureRequest.CONTROL_AF_MODE_CONTINUOUS_PICTURE);camera.createCaptureSession(Arrays.asList(ps,imageReader.getSurface()),new CameraCaptureSession.StateCallback(){public void onConfigured(CameraCaptureSession s){cameraSession=s;try{s.setRepeatingRequest(r.build(),null,cameraHandler);}catch(Exception ignored){}}public void onConfigureFailed(CameraCaptureSession s){}},cameraHandler);}catch(Exception ignored){}}
 private void onImage(ImageReader ir){Image img=ir.acquireLatestImage();if(img==null)return;try{Image.Plane p=img.getPlanes()[0];ByteBuffer b=p.getBuffer();int w=img.getWidth(),h=img.getHeight(),rs=p.getRowStride(),ps=p.getPixelStride();byte[] y=new byte[w*h];for(int yy=0;yy<h;yy++)for(int xx=0;xx<w;xx++){int idx=yy*rs+xx*ps;if(idx<b.limit())y[yy*w+xx]=b.get(idx);}CameraSense.Reading q=cameraSense.process(y,w,h);visualMotion=q.motion;cameraLightChange=q.lightChange;leftMotion=q.leftMotion;rightMotion=q.rightMotion;}finally{img.close();}}
 private final Runnable tick=new Runnable(){public void run(){float combinedLight=Math.max(lightDelta,cameraLightChange);CrossSenseEngine.Prediction cp=cross.update(visualMotion,audioEnergy,vibration,rotation,magnetic,combinedLight);float ev=blindMode==1?cp.predictedVisual:visualMotion,ea=blindMode==2?cp.predictedAudio:audioEnergy;FusionEngine.Percept p=fusion.fuse(ev,ea,vibration,rotation,magnetic,combinedLight);state.setText(p.statement);detail.setText(p.detail);field.setPercept(p);String x;if(blindMode==1)x="BLIND VISION • predicted sight agreement "+Math.round(cp.visualAgreement*100)+"%";else if(blindMode==2)x="BLIND HEARING • predicted sound agreement "+Math.round(cp.audioAgreement*100)+"%";else{x=Math.abs(leftMotion-rightMotion)<.03f?"Visual motion balanced":leftMotion>rightMotion?"Visual movement stronger LEFT":"Visual movement stronger RIGHT";x+=" • V↔Ω "+Math.round(cp.visualAgreement*100)+"% • A↔Ω "+Math.round(cp.audioAgreement*100)+"%";}crossReadout.setText(x);if((p.statement.contains("COHERENT")||p.statement.contains("UNKNOWN"))&&!p.statement.equals(lastSpoken)&&System.currentTimeMillis()-lastSpeak>4000){if(ttsReady)tts.speak(p.statement+". "+p.detail,TextToSpeech.QUEUE_FLUSH,null,"omega_event");lastSpoken=p.statement;lastSpeak=System.currentTimeMillis();}vibration*=.78f;rotation*=.82f;lightDelta*=.75f;cameraLightChange*=.82f;ui.postDelayed(this,160);}};
 private void closeCamera(){try{if(cameraSession!=null)cameraSession.close();}catch(Exception ignored){}try{if(imageReader!=null)imageReader.close();}catch(Exception ignored){}try{if(camera!=null)camera.close();}catch(Exception ignored){}cameraSession=null;imageReader=null;camera=null;}
 @Override public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);if(r==REQ&&permissionsReady())startPerception();else crossReadout.setText("Camera + microphone permissions are needed for full synesthesia mode.");}private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
}
